name: Expo OTA Update

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Baixa o código do repositório
      - uses: actions/checkout@v3

      # Configura Node.js com cache (mais rápido)
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # Instala Expo + EAS CLI
      - uses: expo/expo-github-action@v8
        with:
          expo-version: latest # <--- adiciona essa linha
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # Instala dependências
      - run: npm install --frozen-lockfile

      # Publica a atualização OTA
      - run: eas update --channel preview --message "Preview update via GitHub Actions"
